#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init -q --no-repo-verify --depth=1 -u git://github.com/crdroidandroid/android.git -b 11.0  -g default,-device,-mips,-darwin,-notdefault

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 -q || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8 -q

git clone https://github.com/JamieHoSzeYui/device_xiaomi_sm6250-common -b 11-prebuilt device/xiaomi/sm6250-common 
git clone https://github.com/JamieHoSzeYui/device_xiaomi_miatoll device/xiaomi/miatoll 
git clone https://github.com/JamieHoSzeYui/vendor_xiaomi_miatoll --depth=1 --single-branch vendor/xiaomi/miatoll 
git clone https://github.com/JamieHoSzeYui/vendor_xiaomi_sm6250-common --depth=1 --single-branch vendor/xiaomi/sm6250-common 
# git clone https://github.com/JamieHoSzeYui/android_kernel_xiaomi_sm6250 --depth=1 --single-branch kernel/xiaomi/sm6250  
